name: CI Pipeline

env:
  NODE_ENV: ci

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      target:
        type: choice
        options:
          - dev
          - staging
          - prod
        default: dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    outputs:
      test-report: ${{steps.test-step.outputs.report}}
    steps:
      - name: ch4eckout code
        uses: actions/checkout@v6
      - name: running tests
        id: test-step
        run: |
          npm test
          echo "report=report-2025.html" >> $GITHUB_OUTPUT

  release:
    if: ${{ (github.event_name == 'push' && github.ref_name == 'main') || github.event_name == 'workflow_dispatch'}}
    needs:
      - test
    uses: ./.github/workflows/reusable-release.yaml
    with:
      report: ${{ needs.test.outputs.test-report }}
    secrets:
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}

  notify:
    runs-on: ubuntu-latest
    needs: [lint, test, release]
    if: failure()
    steps:
      - name: Printing actor
        run: |
          echo "Workflow ${{github.workflow}} failed. Commit: ${{github.sha}}, triggered by: ${{ github.actor }}"
